name: cmip6slr
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - bioconda::snakemake=9.7.1
  - bioconda::snakemake-executor-plugin-slurm=1.4.0
  - conda-forge::pulp=2.7.0
  - conda-forge::pip-tools
  - conda-forge::gdal=3.8.5
  - conda-forge::proj
  - conda-forge::geos
  - conda-forge::esmpy
  - conda-forge::xesmf
  - conda-forge::libgdal
  - conda-forge::netCDF4
  - conda-forge::esgf-pyclient
  - conda-forge::sqlite
  # - conda-forge::h5py=3.14.0
  # - conda-forge::h5netcdf=1.6.4
  - pip:
      - affine==2.4.0
      - asttokens==3.0.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - bs4==0.0.2
      - build==1.2.2.post1
      - cachetools==5.5.1
      - Cartopy==0.24.1
      - cdsapi==0.7.5
      - certifi==2025.1.31
      - cf_xarray==0.10.0
      - cffi==1.17.1
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask[array,dataframe,distributed]==2024.11.2
      - datapi==0.2.0
      - debugpy==1.8.12
      - decorator==5.1.1
      - distributed==2024.11.2
      - earthengine-api==1.5.1
      - executing==2.2.0
      - f90nml==1.4.4
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.56.0
      - fsspec==2025.2.0
      - future==1.0.0
      - geopandas==1.0.1
      - ghp-import==2.1.0
      - globalwarmingpotentials==0.11.1
      - google-api-core==2.24.1
      - google-api-python-client==2.160.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-cloud-core==2.4.1
      - google-cloud-storage==3.0.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - griffe==1.5.6
      - h11==0.14.0
      - httplib2==0.22.0
      - hvplot==0.12.1
      - hydroerr==1.24
      - idna==3.10
      - importlib_metadata==8.6.1
      - ipykernel==6.29.5
      - ipython==8.32.0
      - jedi==0.19.2
      - Jinja2==3.1.5
      - joblib==1.4.2
      - jsonpointer==2.1
      - jupyter_client==8.6.3
      - jupyter_core==5.7.2
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - locket==1.0.0
      - Markdown==3.7
      - MarkupSafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.3.0
      - mkdocs-gen-files==0.5.0
      - mkdocs-get-deps==0.2.0
      - mkdocs-literate-nav==0.6.1
      - mkdocs-section-index==0.3.9
      - mkdocstrings==0.28.0
      - mkdocstrings-python==1.14.6
      - msgpack==1.1.0
      - multiurl==0.3.3
      - nest-asyncio==1.6.0
      - openscm-units==0.6.3
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - pandas-datapackage-reader==0.18.0
      - parso==0.8.4
      - partd==1.4.2
      - pathspec==0.12.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - Pint==0.24.4
      - Pint-Pandas==0.7.1
      - pint-xarray==0.4
      - pip-tools==7.4.1
      - platformdirs==4.3.6
      - pluggy
      - polars==1.36.1
      - pooch==1.8.2
      - prompt_toolkit==3.0.50
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure_eval==0.2.3
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.1
      - pycparser==2.22
      - Pygments==2.19.1
      - pymagicc==2.1.5
      - pymdown-extensions==10.14.3
      - pyogrio==0.10.0
      - pyparsing==3.2.1
      - pyproj==3.7.0
      - pyproject_hooks==1.2.0
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - PyYAML==6.0.2
      - pyyaml_env_tag==0.1
      - pyzmq==26.2.1
      - radian==0.6.13
      - rasterio==1.4.3
      - rchitect==0.4.7
      - regionmask==0.13.0
      - rioxarray==0.18.2
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - scmdata==0.17.0
      - seaborn==0.13.2
      - selenium==4.28.1
      - shapely==2.0.7
      - similaritymeasures==1.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tblib==3.0.0
      - threadpoolctl==3.5.0
      - toolz==1.0.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trio==0.28.0
      - trio-websocket==0.11.1
      - typing_extensions==4.12.2
      - tzdata==2025.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - versioneer==0.29
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - wxee==0.4.2
      - xarray==2025.1.2
      - xarrayutils==2.0.1
      - xclim==0.59.1
      - xgcm==0.6.1
      - xmip==0.7.2
      - xsdba==0.5.0
      - zarr==2.18.7
      - zict==3.0.0
      - zipp==3.21.0
